services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_graphql
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres
    container_name: postgres_prisma
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nestjs
    volumes:
      - ./db:/var/lib/postgresql
